# Generated by Django 2.2 on 2019-06-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Изображение'),
        ),
    ]
