# Generated by Django 2.2 on 2019-06-26 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190626_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='products/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
